// react-todos/src/components/TodoItem.jsx
export default function TodoItem(props) {
  const { item, toggleComplete, deleteTodo } = props;
  return (
    <li
      key={item.id}
      id={item.id}
      className={item.completed ? "completed" : null}
      onClick={toggleComplete}
    >
      {item.name}{" "}
      <button id={item.id} onClick={deleteTodo}>
        X
      </button>
    </li>
  );
}

// vue-todos/src/components/TodoItem.vue
<template>
  <li
    v-bind:id="this.$props.item.id"
    v-on:click="toggle"
    v-bind:class="this.$props.item.completed ? 'completed' : null"
  >
    {{ this.$props.item.name }}
    <button v-bind:id="this.$props.item.id" v-on:click="deleteClick">X</button>
  </li>
</template>

<script>
export default {
  name: "TodoItem",
  props: {
    item: {
      type: Object,
    },
    toggleComplete: {
      type: Function,
    },
    deleteTodo: {
      type: Function,
    },
  },
  methods: {
    toggle: function(event) {
      this.$props.toggleComplete(event);
    },
    deleteClick: function(event) {
      this.$props.deleteTodo(event);
    },
  },
};
</script>

<style></style>
