// react-todos/src/components/TodoList.jsx
import TodoItem from "./TodoItem.jsx";
export default function TodoList(props) {
  const { toggleComplete, deleteTodo, todos } = props;
  return (
    <ul>
      {todos.map((item) => (
        <TodoItem
          key={item.id}
          item={item}
          toggleComplete={toggleComplete}
          deleteTodo={deleteTodo}
        />
      ))}
    </ul>
  );
}

// vue-todos/src/components/TodoList.vue
<template>
  <ul>
    <li
      v-on:click="toggle"
      v-bind:id="item.id"
      v-bind:key="item.id"
      v-for="item in this.$props.todos"
      v-bind:class="item.completed ? 'completed' : null"
    >
      {{ item.name }}
      <button v-bind:id="item.id" v-on:click="deleteClick">X</button>
    </li>
  </ul>
</template>

<script>
export default {
  name: "TodoList",
  props: {
    todos: {
      type: Array,
    },
    toggleComplete: {
      type: Function,
    },
    deleteTodo: {
      type: Function,
    },
  },
  data: function() {
      return {}
  },
  methods: {
      toggle: function(event) {
          this.$props.toggleComplete(event)
      },
      deleteClick: function(event) {
          this.$props.deleteTodo(event)
      }
  }
};
</script>

<style></style>
