// react-todos/src/components/TodoForm.jsx
import { useState } from "react";

export default function TodoForm(props) {
  const [formValue, setFormValue] = useState("");
  const { todos, setTodos, incrementId, nextId } = props;
  function handleChange(event) {
    setFormValue(event.target.value);
  }

  function handleSubmit(event) {
    event.preventDefault();
    const newTodo = {
      id: nextId,
      name: formValue,
      completed: false,
    };
    setTodos([...todos, newTodo]);
    setFormValue("");
    incrementId();
  }

  return (
    <form onSubmit={handleSubmit}>
      <label htmlFor="newTodo">New Todo </label>
      <input
        id="newTodo"
        name="newTodo"
        value={formValue}
        onChange={handleChange}
        type="text"
      />
      <button type="submit" disabled={formValue.length < 1}>Add</button>
    </form>
  );
}

// vue-todos/src/components/TodoForm.vue
<template>
  <form v-on:submit.prevent @submit="addTodo">
    <label htmlFor="newTodo">New Todo </label>
    <input id="newTodo" name="newTodo" v-model="state.formValue" type="text" />
    <button type="submit" v-bind:disabled="state.formValue.length < 1">
      Add
    </button>
  </form>
</template>

<script>
export default {
  name: "TodoForm",
  props: {
    todos: {
      type: Array,
    },
    handleSubmit: {
      type: Function,
    },
    nextId: {
      type: Number,
    },
    incrementId: {
      type: Function,
    },
  },
  data: function() {
    return {
      state: {
        formValue: "",
      },
    };
  },
  methods: {
    addTodo: function() {
      const newTodo = {
        id: this.$props.nextId,
        name: this.state.formValue,
        completed: false,
      };
      this.handleSubmit(newTodo);
      this.state.formValue = "";
      this.$props.incrementId();
    },
  },
};
</script>

<style></style>
