// react-todos/src/App.js
import { useState } from "react";
import ReactHeader from "./components/ReactHeader.jsx";
import dummyData from "./dummyData.json";

function App() {
  const [todos, setTodos] = useState(dummyData);
  const [formValue, setFormValue] = useState("");

  function handleChange(event) {
    setFormValue(event.target.value);
  }

  function handleSubmit(event) {
    event.preventDefault();
    const newTodo = {
      id: todos[todos.length - 1].id + 1,
      name: formValue,
      completed: false,
    };
    setTodos([...todos, newTodo]);
  }

  function toggleComplete(event) {
    const updateCompleted = todos.map((item) => {
      if (Number(event.target.id) === item.id) {
        return { ...item, completed: !item.completed };
      } else return item;
    });
    setTodos(updateCompleted);
  }

  function deleteCompleted() {
    const filterDeleted = todos.filter((item) => !item.completed);
    setTodos(filterDeleted);
  }

  function deleteTodo(event) {
    event.stopPropagation();
    const removeDeleted = todos.filter((item) => {
      return item.id !== Number(event.target.id);
    });
    setTodos(removeDeleted);
  }

  return (
    <div id="app">
      <ReactHeader message={"Welcome to your ReactJS Todos App"} />

      <form onSubmit={handleSubmit}>
        <label htmlFor="newTodo">New Todo </label>
        <input
          id="newTodo"
          name="newTodo"
          value={formValue}
          onChange={handleChange}
          type="text"
        />
        <button type="submit">Add</button>
      </form>
      <button onClick={deleteCompleted}>Clear Completed</button>
      <ul>
        {todos.map((item) => (
          <li
            key={item.id}
            id={item.id}
            className={item.completed ? "completed" : null}
            onClick={toggleComplete}
          >
            {item.name}{" "}
            <button id={item.id} onClick={deleteTodo}>
              X
            </button>
          </li>
        ))}
      </ul>
    </div>
  );
}

export default App;

// vue-todos/src/App.vue
<template>
  <div id="app">
    <VueHeader message="Welcome to your VueJS Todos App" />

    <form v-on:submit.prevent @submit="handleSubmit">
      <label htmlFor="newTodo">New Todo </label>
      <input
        id="newTodo"
        name="newTodo"
        v-model="state.formValue"
        type="text"
      />
      <button type="submit">Add</button>
    </form>
    <button v-on:click="deleteCompleted">Clear Completed</button>
    <ul>
      <li
        v-on:click="toggleComplete"
        v-bind:id="item.id"
        v-bind:key="item.id"
        v-for="item of state.todos"
        v-bind:class="item.completed ? 'completed' : null"
      >
        {{ item.name }}
        <button v-bind:id="item.id" v-on:click="deleteTodo">X</button>
      </li>
    </ul>
  </div>
</template>

<script>
import VueHeader from "./components/VueHeader.vue";
import dummyData from "./dummyData.json";

export default {
  name: "App",
  components: { VueHeader },
  data: function() {
    return {
      state: {
        todos: dummyData,
        formValue: "",
      },
    };
  },
  methods: {
    handleSubmit: function() {
      const newTodo = {
        id: this.state.todos[this.state.todos.length - 1].id + 1,
        name: this.state.formValue,
        completed: false,
      };
      this.state.todos.push(newTodo);
    },
    toggleComplete: function(event) {
      this.state.todos = this.state.todos.map((item) => {
        if (Number(event.target.id) === item.id) {
          return { ...item, completed: !item.completed };
        } else return item;
      });
    },
    deleteCompleted: function() {
      this.state.todos = this.state.todos.filter((item) => !item.completed);
    },
    deleteTodo: function(event) {
      this.state.todos = this.state.todos.filter(
        (item) => item.id !== Number(event.target.id)
      );
    },
  },
};
</script>

<style>
#app {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen",
    "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue",
    sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
}

ul {
  list-style-type: none;
  padding: 0;
}

li {
  user-select: none;
}

li:hover {
  cursor: pointer;
}

.completed {
  text-decoration: line-through;
}
</style>
